package hexlet.code;

import java.sql.DriverManager;
import java.sql.SQLException;

public class Application {
    // Нужно указывать базовое исключение,
    // потому что выполнение запросов может привести к исключениям
    public static void main(String[] args) throws SQLException {
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:dao")) {
            try (var statement = conn.createStatement()) {
                statement.executeUpdate(
                        """
                        
                                CREATE TABLE users (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            username VARCHAR(255),
                            phone VARCHAR(255)
                        )
                        """);
            }

            var dao = new UserDAO(conn);
            var user = new User("Maria", "888888888");
            System.out.println(user.getId());
            dao.save(user);
            System.out.println(user.getId());

            user.setPhone("999999999");
            dao.save(user);
            var savedUser = dao.find(user.getId()).orElseThrow();
            System.out.println(savedUser.getId().equals(user.getId()));
            System.out.println(savedUser.getPhone());
            System.out.println(dao.find(99L).isEmpty());

            dao.select();

            System.out.println(dao.delete(99L));
            System.out.println(dao.delete(1L));

            dao.select();


        }
    }
    }